/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HeroesIndexRouteImport } from './routes/heroes/index'
import { Route as HeroesHeroIdRouteImport } from './routes/heroes/$heroId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroesIndexRoute = HeroesIndexRouteImport.update({
  id: '/heroes/',
  path: '/heroes/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroesHeroIdRoute = HeroesHeroIdRouteImport.update({
  id: '/heroes/$heroId',
  path: '/heroes/$heroId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/heroes/$heroId': typeof HeroesHeroIdRoute
  '/heroes/': typeof HeroesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/heroes/$heroId': typeof HeroesHeroIdRoute
  '/heroes': typeof HeroesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/heroes/$heroId': typeof HeroesHeroIdRoute
  '/heroes/': typeof HeroesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/heroes/$heroId' | '/heroes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/heroes/$heroId' | '/heroes'
  id: '__root__' | '/' | '/heroes/$heroId' | '/heroes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HeroesHeroIdRoute: typeof HeroesHeroIdRoute
  HeroesIndexRoute: typeof HeroesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heroes/': {
      id: '/heroes/'
      path: '/heroes'
      fullPath: '/heroes/'
      preLoaderRoute: typeof HeroesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heroes/$heroId': {
      id: '/heroes/$heroId'
      path: '/heroes/$heroId'
      fullPath: '/heroes/$heroId'
      preLoaderRoute: typeof HeroesHeroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HeroesHeroIdRoute: HeroesHeroIdRoute,
  HeroesIndexRoute: HeroesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
