/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as HeroIndexRouteImport } from './routes/hero/index'
import { Route as HeroHeroIdRouteImport } from './routes/hero/$heroId'
import { Route as HeroCreateRouteImport } from './routes/hero/create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroIndexRoute = HeroIndexRouteImport.update({
  id: '/hero/',
  path: '/hero/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroHeroIdRoute = HeroHeroIdRouteImport.update({
  id: '/hero/$heroId',
  path: '/hero/$heroId',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroCreateRoute = HeroCreateRouteImport.update({
  id: '/hero/create',
  path: '/hero/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/hero/$heroId': typeof HeroHeroIdRoute
  '/hero/create': typeof HeroCreateRoute
  '/hero/': typeof HeroIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/hero/$heroId': typeof HeroHeroIdRoute
  '/hero/create': typeof HeroCreateRoute
  '/hero': typeof HeroIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/hero/$heroId': typeof HeroHeroIdRoute
  '/hero/create': typeof HeroCreateRoute
  '/hero/': typeof HeroIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/hero/$heroId' | '/hero/create' | '/hero/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/hero/$heroId' | '/hero/create' | '/hero'
  id: '__root__' | '/' | '/about' | '/hero/$heroId' | '/hero/create' | '/hero/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HeroHeroIdRoute: typeof HeroHeroIdRoute
  HeroCreateRoute: typeof HeroCreateRoute
  HeroIndexRoute: typeof HeroIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero/': {
      id: '/hero/'
      path: '/hero'
      fullPath: '/hero/'
      preLoaderRoute: typeof HeroIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero/$heroId': {
      id: '/hero/$heroId'
      path: '/hero/$heroId'
      fullPath: '/hero/$heroId'
      preLoaderRoute: typeof HeroHeroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero/create': {
      id: '/hero/create'
      path: '/hero/create'
      fullPath: '/hero/create'
      preLoaderRoute: typeof HeroCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HeroHeroIdRoute: HeroHeroIdRoute,
  HeroCreateRoute: HeroCreateRoute,
  HeroIndexRoute: HeroIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
